[ { athleteName: 'Giovanni G.',
    athleteRank: 1,
    finishTime: '2:22:18',
    finishTimeInMinutes: 142,
    finishPace: '3:22/km',
    athleteGender: 'M',
    athleteAge: 37 },
  { athleteName: 'Yohann PRUVOT',
    athleteRank: 2,
    finishTime: '2:26:50',
    finishTimeInMinutes: 146,
    finishPace: '3:29/km',
    athleteGender: 'M',
    athleteAge: 32 },
  { athleteName: 'Adrien Guiomar',
    athleteRank: 3,
    finishTime: '2:30:44',
    finishTimeInMinutes: 150,
    finishPace: '3:34/km',
    athleteGender: 'M',
    athleteAge: 34 },
  { athleteName: 'Matt Lawder',
    athleteRank: 4,
    finishTime: '2:30:49',
    finishTimeInMinutes: 150,
    finishPace: '3:34/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Jerry Faulkner',
    athleteRank: 5,
    finishTime: '2:31:49',
    finishTimeInMinutes: 151,
    finishPace: '3:36/km',
    athleteGender: '',
    athleteAge: NaN },
  { athleteName: 'Trevor Middleton',
    athleteRank: 6,
    finishTime: '2:32:37',
    finishTimeInMinutes: 152,
    finishPace: '3:37/km',
    athleteGender: 'M',
    athleteAge: 30 },
  { athleteName: 'michael wardian',
    athleteRank: 7,
    finishTime: '2:33:34',
    finishTimeInMinutes: 153,
    finishPace: '3:38/km',
    athleteGender: 'M',
    athleteAge: 42 },
  { athleteName: 'David Roeske',
    athleteRank: 8,
    finishTime: '2:34:49',
    finishTimeInMinutes: 154,
    finishPace: '3:40/km',
    athleteGender: 'M',
    athleteAge: 36 },
  { athleteName: 'Justin K.',
    athleteRank: 9,
    finishTime: '2:36:07',
    finishTimeInMinutes: 156,
    finishPace: '3:42/km',
    athleteGender: '',
    athleteAge: NaN },
  { athleteName: 'Gilles  Rubio',
    athleteRank: 10,
    finishTime: '2:36:10',
    finishTimeInMinutes: 156,
    finishPace: '3:42/km',
    athleteGender: 'M',
    athleteAge: 36 },
  { athleteName: 'George Darden',
    athleteRank: 11,
    finishTime: '2:36:47',
    finishTimeInMinutes: 156,
    finishPace: '3:43/km',
    athleteGender: 'M',
    athleteAge: 42 },
  { athleteName: 'Jeremiah E.',
    athleteRank: 12,
    finishTime: '2:36:57',
    finishTimeInMinutes: 156,
    finishPace: '3:43/km',
    athleteGender: 'M',
    athleteAge: 35 },
  { athleteName: 'Nathanael Bordes',
    athleteRank: 13,
    finishTime: '2:37:41',
    finishTimeInMinutes: 157,
    finishPace: '3:44/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Carlo A.',
    athleteRank: 14,
    finishTime: '2:37:47',
    finishTimeInMinutes: 157,
    finishPace: '3:44/km',
    athleteGender: 'M',
    athleteAge: 36 },
  { athleteName: 'Phil Shaw',
    athleteRank: 15,
    finishTime: '2:38:02',
    finishTimeInMinutes: 158,
    finishPace: '3:45/km',
    athleteGender: 'M',
    athleteAge: 32 },
  { athleteName: 'Jordan Andersen',
    athleteRank: 16,
    finishTime: '2:38:11',
    finishTimeInMinutes: 158,
    finishPace: '3:45/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Tim B.',
    athleteRank: 17,
    finishTime: '2:38:38',
    finishTimeInMinutes: 158,
    finishPace: '3:46/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'alex walsh',
    athleteRank: 18,
    finishTime: '2:39:01',
    finishTimeInMinutes: 159,
    finishPace: '3:46/km',
    athleteGender: 'M',
    athleteAge: 42 },
  { athleteName: 'Euan Geddes',
    athleteRank: 19,
    finishTime: '2:39:11',
    finishTimeInMinutes: 159,
    finishPace: '3:46/km',
    athleteGender: 'M',
    athleteAge: 45 },
  { athleteName: 'Jonathon L.',
    athleteRank: 20,
    finishTime: '2:39:37',
    finishTimeInMinutes: 159,
    finishPace: '3:47/km',
    athleteGender: 'M',
    athleteAge: 32 },
  { athleteName: 'Hunter H.',
    athleteRank: 21,
    finishTime: '2:39:51',
    finishTimeInMinutes: 159,
    finishPace: '3:47/km',
    athleteGender: 'M',
    athleteAge: 28 },
  { athleteName: 'Alec DePaolis',
    athleteRank: 22,
    finishTime: '2:40:44',
    finishTimeInMinutes: 160,
    finishPace: '3:49/km',
    athleteGender: 'M',
    athleteAge: 22 },
  { athleteName: 'Sjur Molstad',
    athleteRank: 23,
    finishTime: '2:40:49',
    finishTimeInMinutes: 160,
    finishPace: '3:49/km',
    athleteGender: 'M',
    athleteAge: 34 },
  { athleteName: 'Ian Blackwell',
    athleteRank: 24,
    finishTime: '2:40:50',
    finishTimeInMinutes: 160,
    finishPace: '3:49/km',
    athleteGender: 'M',
    athleteAge: 30 },
  { athleteName: 'Sam Teigen',
    athleteRank: 25,
    finishTime: '2:40:52',
    finishTimeInMinutes: 160,
    finishPace: '3:49/km',
    athleteGender: 'M',
    athleteAge: 42 },
  { athleteName: 'Vidar Hansen',
    athleteRank: 26,
    finishTime: '2:41:00',
    finishTimeInMinutes: 161,
    finishPace: '3:49/km',
    athleteGender: 'M',
    athleteAge: 37 },
  { athleteName: 'Kristopher S.',
    athleteRank: 27,
    finishTime: '2:41:34',
    finishTimeInMinutes: 161,
    finishPace: '3:50/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Peter H.',
    athleteRank: 28,
    finishTime: '2:41:39',
    finishTimeInMinutes: 161,
    finishPace: '3:50/km',
    athleteGender: 'M',
    athleteAge: 38 },
  { athleteName: 'Andrew K.',
    athleteRank: 29,
    finishTime: '2:41:46',
    finishTimeInMinutes: 161,
    finishPace: '3:50/km',
    athleteGender: 'M',
    athleteAge: 28 },
  { athleteName: 'Joe Burnett',
    athleteRank: 30,
    finishTime: '2:41:51',
    finishTimeInMinutes: 161,
    finishPace: '3:50/km',
    athleteGender: 'M',
    athleteAge: 37 },
  { athleteName: 'Douglas Pierce',
    athleteRank: 31,
    finishTime: '2:42:09',
    finishTimeInMinutes: 162,
    finishPace: '3:51/km',
    athleteGender: 'M',
    athleteAge: 34 },
  { athleteName: 'David Proffitt',
    athleteRank: 32,
    finishTime: '2:42:15',
    finishTimeInMinutes: 162,
    finishPace: '3:51/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Enrique S.',
    athleteRank: 33,
    finishTime: '2:42:16',
    finishTimeInMinutes: 162,
    finishPace: '3:51/km',
    athleteGender: 'M',
    athleteAge: 30 },
  { athleteName: 'Jann Post',
    athleteRank: 34,
    finishTime: '2:42:17',
    finishTimeInMinutes: 162,
    finishPace: '3:51/km',
    athleteGender: 'M',
    athleteAge: 36 },
  { athleteName: 'Emmett Saulnier',
    athleteRank: 35,
    finishTime: '2:42:30',
    finishTimeInMinutes: 162,
    finishPace: '3:51/km',
    athleteGender: 'M',
    athleteAge: 21 },
  { athleteName: 'Brian F.',
    athleteRank: 36,
    finishTime: '2:42:35',
    finishTimeInMinutes: 162,
    finishPace: '3:51/km',
    athleteGender: 'M',
    athleteAge: 38 },
  { athleteName: 'Mathieu Blanchard',
    athleteRank: 37,
    finishTime: '2:42:35',
    finishTimeInMinutes: 162,
    finishPace: '3:51/km',
    athleteGender: 'M',
    athleteAge: 29 },
  { athleteName: 'Audun Nordtveit',
    athleteRank: 38,
    finishTime: '2:42:42',
    finishTimeInMinutes: 162,
    finishPace: '3:51/km',
    athleteGender: 'M',
    athleteAge: 28 },
  { athleteName: 'Derek G.',
    athleteRank: 39,
    finishTime: '2:42:43',
    finishTimeInMinutes: 162,
    finishPace: '3:51/km',
    athleteGender: 'M',
    athleteAge: 30 },
  { athleteName: 'Paul Gaimster',
    athleteRank: 40,
    finishTime: '2:43:26',
    finishTimeInMinutes: 163,
    finishPace: '3:52/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Greg Rotman',
    athleteRank: 41,
    finishTime: '2:43:31',
    finishTimeInMinutes: 163,
    finishPace: '3:53/km',
    athleteGender: 'M',
    athleteAge: 38 },
  { athleteName: 'Timothy Clarke',
    athleteRank: 42,
    finishTime: '2:43:36',
    finishTimeInMinutes: 163,
    finishPace: '3:53/km',
    athleteGender: 'M',
    athleteAge: 33 },
  { athleteName: 'Matt W.',
    athleteRank: 43,
    finishTime: '2:43:40',
    finishTimeInMinutes: 163,
    finishPace: '3:53/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Eduardo F.',
    athleteRank: 44,
    finishTime: '2:43:59',
    finishTimeInMinutes: 163,
    finishPace: '3:53/km',
    athleteGender: 'M',
    athleteAge: 42 },
  { athleteName: 'Flo F',
    athleteRank: 45,
    finishTime: '2:44:09',
    finishTimeInMinutes: 164,
    finishPace: '3:53/km',
    athleteGender: 'M',
    athleteAge: 29 },
  { athleteName: 'Mike Treder',
    athleteRank: 46,
    finishTime: '2:44:15',
    finishTimeInMinutes: 164,
    finishPace: '3:54/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Jacob Frandsen',
    athleteRank: 47,
    finishTime: '2:44:19',
    finishTimeInMinutes: 164,
    finishPace: '3:54/km',
    athleteGender: 'M',
    athleteAge: 36 },
  { athleteName: 'Peter Augustine Kazery',
    athleteRank: 48,
    finishTime: '2:44:41',
    finishTimeInMinutes: 164,
    finishPace: '3:54/km',
    athleteGender: 'M',
    athleteAge: 25 },
  { athleteName: 'Matthew Blagg',
    athleteRank: 49,
    finishTime: '2:44:41',
    finishTimeInMinutes: 164,
    finishPace: '3:54/km',
    athleteGender: 'M',
    athleteAge: 37 },
  { athleteName: 'Daniel Seymour K',
    athleteRank: 50,
    finishTime: '2:44:47',
    finishTimeInMinutes: 164,
    finishPace: '3:54/km',
    athleteGender: 'M',
    athleteAge: 30 },
  { athleteName: 'nic baddiley',
    athleteRank: 51,
    finishTime: '2:44:50',
    finishTimeInMinutes: 164,
    finishPace: '3:54/km',
    athleteGender: 'M',
    athleteAge: 41 },
  { athleteName: 'Rune Busch',
    athleteRank: 52,
    finishTime: '2:44:52',
    finishTimeInMinutes: 164,
    finishPace: '3:54/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Hector R.',
    athleteRank: 53,
    finishTime: '2:45:00',
    finishTimeInMinutes: 165,
    finishPace: '3:55/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Patrick Cutter',
    athleteRank: 54,
    finishTime: '2:45:27',
    finishTimeInMinutes: 165,
    finishPace: '3:55/km',
    athleteGender: 'M',
    athleteAge: 28 },
  { athleteName: 'Bob L.',
    athleteRank: 55,
    finishTime: '2:45:40',
    finishTimeInMinutes: 165,
    finishPace: '3:56/km',
    athleteGender: 'M',
    athleteAge: 32 },
  { athleteName: 'zach huseby',
    athleteRank: 56,
    finishTime: '2:45:47',
    finishTimeInMinutes: 165,
    finishPace: '3:56/km',
    athleteGender: 'M',
    athleteAge: 44 },
  { athleteName: 'Shelby Anderson',
    athleteRank: 57,
    finishTime: '2:45:58',
    finishTimeInMinutes: 165,
    finishPace: '3:56/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'James M.',
    athleteRank: 58,
    finishTime: '2:45:58',
    finishTimeInMinutes: 165,
    finishPace: '3:56/km',
    athleteGender: 'M',
    athleteAge: 39 },
  { athleteName: 'Ben Short',
    athleteRank: 59,
    finishTime: '2:46:12',
    finishTimeInMinutes: 166,
    finishPace: '3:56/km',
    athleteGender: 'M',
    athleteAge: 28 },
  { athleteName: 'Luciano Medina',
    athleteRank: 60,
    finishTime: '2:46:44',
    finishTimeInMinutes: 166,
    finishPace: '3:57/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Shihan Wijeyeratne',
    athleteRank: 61,
    finishTime: '2:46:53',
    finishTimeInMinutes: 166,
    finishPace: '3:57/km',
    athleteGender: 'M',
    athleteAge: 23 },
  { athleteName: 'Timothy Buse',
    athleteRank: 62,
    finishTime: '2:47:00',
    finishTimeInMinutes: 167,
    finishPace: '3:57/km',
    athleteGender: 'M',
    athleteAge: 32 },
  { athleteName: 'Jon F.',
    athleteRank: 63,
    finishTime: '2:47:06',
    finishTimeInMinutes: 167,
    finishPace: '3:58/km',
    athleteGender: 'M',
    athleteAge: 38 },
  { athleteName: 'EDUARDO ARENAL',
    athleteRank: 64,
    finishTime: '2:47:08',
    finishTimeInMinutes: 167,
    finishPace: '3:58/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Fred Goris',
    athleteRank: 65,
    finishTime: '2:47:08',
    finishTimeInMinutes: 167,
    finishPace: '3:58/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'gary holt',
    athleteRank: 66,
    finishTime: '2:47:12',
    finishTimeInMinutes: 167,
    finishPace: '3:58/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Kallie Burger',
    athleteRank: 67,
    finishTime: '2:47:18',
    finishTimeInMinutes: 167,
    finishPace: '3:58/km',
    athleteGender: 'M',
    athleteAge: 36 },
  { athleteName: 'Philippe MARZIN',
    athleteRank: 68,
    finishTime: '2:47:18',
    finishTimeInMinutes: 167,
    finishPace: '3:58/km',
    athleteGender: 'M',
    athleteAge: 45 },
  { athleteName: 'Sondre Skjelvik',
    athleteRank: 69,
    finishTime: '2:47:19',
    finishTimeInMinutes: 167,
    finishPace: '3:58/km',
    athleteGender: 'M',
    athleteAge: 25 },
  { athleteName: 'Austin Taylor',
    athleteRank: 70,
    finishTime: '2:47:28',
    finishTimeInMinutes: 167,
    finishPace: '3:58/km',
    athleteGender: 'M',
    athleteAge: 28 },
  { athleteName: 'Julio Vela',
    athleteRank: 71,
    finishTime: '2:47:31',
    finishTimeInMinutes: 167,
    finishPace: '3:58/km',
    athleteGender: 'M',
    athleteAge: 27 },
  { athleteName: 'Akira Nishimura',
    athleteRank: 72,
    finishTime: '2:47:55',
    finishTimeInMinutes: 167,
    finishPace: '3:59/km',
    athleteGender: 'M',
    athleteAge: 41 },
  { athleteName: 'Shaun Osborne',
    athleteRank: 73,
    finishTime: '2:47:56',
    finishTimeInMinutes: 167,
    finishPace: '3:59/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Neal Naughton',
    athleteRank: 74,
    finishTime: '2:48:00',
    finishTimeInMinutes: 168,
    finishPace: '3:59/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'David Scholl',
    athleteRank: 75,
    finishTime: '2:48:04',
    finishTimeInMinutes: 168,
    finishPace: '3:59/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Jeremy Barry',
    athleteRank: 76,
    finishTime: '2:48:12',
    finishTimeInMinutes: 168,
    finishPace: '3:59/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Matt Collins',
    athleteRank: 77,
    finishTime: '2:48:18',
    finishTimeInMinutes: 168,
    finishPace: '3:59/km',
    athleteGender: 'M',
    athleteAge: 26 },
  { athleteName: 'Douglas Tsao',
    athleteRank: 78,
    finishTime: '2:48:24',
    finishTimeInMinutes: 168,
    finishPace: '3:59/km',
    athleteGender: 'M',
    athleteAge: 43 },
  { athleteName: 'Addison Albin',
    athleteRank: 79,
    finishTime: '2:48:30',
    finishTimeInMinutes: 168,
    finishPace: '4:00/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'James B.',
    athleteRank: 80,
    finishTime: '2:48:32',
    finishTimeInMinutes: 168,
    finishPace: '4:00/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Garrett Wanjala',
    athleteRank: 81,
    finishTime: '2:48:33',
    finishTimeInMinutes: 168,
    finishPace: '4:00/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Julien S.',
    athleteRank: 82,
    finishTime: '2:48:37',
    finishTimeInMinutes: 168,
    finishPace: '4:00/km',
    athleteGender: 'M',
    athleteAge: 34 },
  { athleteName: 'Erik Bergersen',
    athleteRank: 83,
    finishTime: '2:48:46',
    finishTimeInMinutes: 168,
    finishPace: '4:00/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Russ L.',
    athleteRank: 84,
    finishTime: '2:48:49',
    finishTimeInMinutes: 168,
    finishPace: '4:00/km',
    athleteGender: 'M',
    athleteAge: 34 },
  { athleteName: 'S. Y.',
    athleteRank: 85,
    finishTime: '2:48:51',
    finishTimeInMinutes: 168,
    finishPace: '4:00/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Bob Scheungrab',
    athleteRank: 86,
    finishTime: '2:48:51',
    finishTimeInMinutes: 168,
    finishPace: '4:00/km',
    athleteGender: 'M',
    athleteAge: 41 },
  { athleteName: 'Sebastian Lau Sørensen',
    athleteRank: 87,
    finishTime: '2:48:52',
    finishTimeInMinutes: 168,
    finishPace: '4:00/km',
    athleteGender: 'M',
    athleteAge: 32 },
  { athleteName: 'Bram Som',
    athleteRank: 88,
    finishTime: '2:48:52',
    finishTimeInMinutes: 168,
    finishPace: '4:00/km',
    athleteGender: 'M',
    athleteAge: 37 },
  { athleteName: 'Rob Veldman',
    athleteRank: 89,
    finishTime: '2:49:00',
    finishTimeInMinutes: 169,
    finishPace: '4:00/km',
    athleteGender: 'M',
    athleteAge: 28 },
  { athleteName: 'Zach S.',
    athleteRank: 90,
    finishTime: '2:49:14',
    finishTimeInMinutes: 169,
    finishPace: '4:01/km',
    athleteGender: 'M',
    athleteAge: 29 },
  { athleteName: 'Xavier F.',
    athleteRank: 91,
    finishTime: '2:49:20',
    finishTimeInMinutes: 169,
    finishPace: '4:01/km',
    athleteGender: 'M',
    athleteAge: 40 },
  { athleteName: 'Santiago RS',
    athleteRank: 92,
    finishTime: '2:49:23',
    finishTimeInMinutes: 169,
    finishPace: '4:01/km',
    athleteGender: 'M',
    athleteAge: 26 },
  { athleteName: 'Henk Verdonkschot',
    athleteRank: 93,
    finishTime: '2:49:26',
    finishTimeInMinutes: 169,
    finishPace: '4:01/km',
    athleteGender: 'M',
    athleteAge: 61 },
  { athleteName: 'Matthew Urbanski',
    athleteRank: 94,
    finishTime: '2:49:34',
    finishTimeInMinutes: 169,
    finishPace: '4:01/km',
    athleteGender: 'M',
    athleteAge: 36 },
  { athleteName: 'Patrick Gaynor',
    athleteRank: 95,
    finishTime: '2:49:38',
    finishTimeInMinutes: 169,
    finishPace: '4:01/km',
    athleteGender: 'M',
    athleteAge: 37 },
  { athleteName: 'Katsu T.',
    athleteRank: 96,
    finishTime: '2:49:50',
    finishTimeInMinutes: 169,
    finishPace: '4:01/km',
    athleteGender: 'M',
    athleteAge: NaN },
  { athleteName: 'Daniel Roy',
    athleteRank: 97,
    finishTime: '2:49:51',
    finishTimeInMinutes: 169,
    finishPace: '4:02/km',
    athleteGender: 'M',
    athleteAge: 27 },
  { athleteName: 'Sebastian W.',
    athleteRank: 98,
    finishTime: '2:49:56',
    finishTimeInMinutes: 169,
    finishPace: '4:02/km',
    athleteGender: 'M',
    athleteAge: 33 },
  { athleteName: 'Julien Le Discot',
    athleteRank: 99,
    finishTime: '2:50:00',
    finishTimeInMinutes: 170,
    finishPace: '4:02/km',
    athleteGender: 'M',
    athleteAge: 31 },
  { athleteName: 'Jillian P.',
    athleteRank: 100,
    finishTime: '2:50:06',
    finishTimeInMinutes: 170,
    finishPace: '4:02/km',
    athleteGender: 'F',
    athleteAge: NaN },
  ... 200 more items ]
